### ISSUE TITLE
Short term object interaction sampling & "Time_to_contact" 

### ISSUE THREAD

**Issue by MiaQiu** [EGO4D/forecasting#20]
Hello,

I have a question regarding sampling method for Short-Term Object Interaction Anticipation task.

In the paper, section J.3 Data Annotation and Figure 54, it's stated that "For a given action i, we sample m frames at regular intervals. If we set m = 4 and \alpha= 0.5, we label the frame of contact as well as 4 frames along a segment of 2s preceding the beginning of the action at a framerate of 2fps". 

According to the sampling method described above, I would expect the "time_to_contact" to be 0.5s, 1s, 1.5s and 2s for 4 frames sampled. However, this seems not the case shown in the annotation. The frames are rather randomly sampled (with 0.5s intervals). For example, there are 4 frames with contact time 0.3s, 0.8s, 1.3s, and 1.8s; another example 0.533333333s, 1.033333333s, 1.533333333s, and 2.033333333s.

May I confirm how frames are sampled for Short-Term Object Interaction Anticipation?

Thank you very much!
Mia

**Comment by antoninofurnari** [comment]
Dear Mia,

You are right, there is a discrepancy between what we wrote in the paper and what we ended up doing. Indeed, the initial plan was to label 4 frames sampled evenly going backward from the contact frame. This would have led to fixed time to contact as you noted above, which would limited the diversity of the ground truth. 

Instead, we opted for sampling these points starting from PRE, rather than from the contact frame. Since the distance between PRE and the contact frame is variable, the frames seem to be sampled "randomly", but they are not. We probably just forgot to update this in the draft of the paper as we changed these labeling details. 

Hope this clarifies how frames are sampled for STA, but please let me know if there are still doubts.

best,
Antonino

**Comment by MiaQiu** [comment]
> 
Dear Antonino,

Thank you so much for the details, that explains.

Cheers,
Mia
