### ISSUE TITLE
An Error related to Long-Term Action Anticipation

### ISSUE THREAD

**Issue by hirokiyazaki** [EGO4D/forecasting#23]
When I tried code of Downsampling video clips, I got an error as shown below.

           sbatch: error: Invalid directive found in batch script: partition>

I looked up this error and it was an error due to whitespace, but I am using the code of forecasting/tools/long_term_anticipation/resize_clips.sh without changing it.
Perhaps the cause was the whitespace between slurm and partition on line 13.
I would like to know if I should change the content of line 13, or if I should add some other library, or if this is caused by something else.

**Comment by Tushar-N** [comment]
> I would like to know if I should change the content of line 13, or if I should add some other library, or if this is caused by something else.

Line 13 should be changed to use the partition name on your cluster (instead of `<slurm partition>`). [sinfo](https://slurm.schedmd.com/sinfo.html) should point you to what the options are here. Note that when eventually training, the partition info needs to be updated [here](https://github.com/EGO4D/forecasting/blob/132e81cc85b30d866ea12547403247053b3560e7/scripts/run_lta.py#L265) too.
