### ISSUE TITLE
Features for Long Term Forecasting

### ISSUE THREAD

**Issue by Evm7** [EGO4D/forecasting#5]
Hi! I am planning to use the features from slowfast8x8_r101_k400 defined in "https://ego4d-data.org/docs/data/features/" and downloaded using the CLI as the baseline for the Forecasting. However, it does not seem trivial to relate the extracted features from videos to the annotated clips from the LTA Benchmark. Is there any tool provided or can you provide any information on how to realate them.

As an example, clip with clip_uid='2acc5677-5972-4e4a-833a-bb12b76c33f6' has a clip_parent parameter in the annotations that ranges from frame 8759 to 17534, thus with length 8775. However, the feature .pt file with this video uid contain dimension 1095.
![image](https://user-images.githubusercontent.com/43722285/164017594-49a2276b-be69-4ce2-99bd-e4f2cfd8bc30.png)
![image](https://user-images.githubusercontent.com/43722285/164017711-eeb47578-f74f-41d5-b74d-821c685e3cde.png)

How can I extract the features for this clip from the global video features? There is a Window=32 (defined in https://ego4d-data.org/docs/data/features/) but I can still not see how they could be mapped.

Really thanks!

**Comment by HarshayuGirase** [comment]
+1, does the current codebase only handle training from videos directly? If there's code to train using pre-extracted features that would be really helpful!

**Comment by srijandas07** [comment]
+1, similar to the action detection frameworks on Charades kind of datasets.
Though it might loose the spatial resolution but could make use of more temporal contextual information than (k=8 as mentioned in the paper).

**Comment by Tushar-N** [comment]
> +1, does the current codebase only handle training from videos directly

Yes, this is correct. The current codebase reads .mp4 files directly and extracts the relevant features. This is useful because (1) the start/end times of the clip do not match the precomputed clip feature boundaries exactly (2) during training, frames are sampled with random offsets (for data augmentation).  

> Though it might loose the spatial resolution but could make use of more temporal contextual information than (k=8 as mentioned in the paper).

Agreed. The K=8 models also sample frames from the .mp4 container, but cannot accommodate larger temporal contexts due to memory constraints. 

> As an example, clip with clip_uid='2acc5677-5972-4e4a-833a-bb12b76c33f6' has a clip_parent parameter in the annotations that ranges from frame 8759 to 17534, thus with length 8775. However, the feature .pt file with this video uid contain dimension 1095.

The 1095 corresponds to the features generated for the full video (keyed by video_uid, not clip_uid). Selecting features that occur within the boundaries `[clip_parent_start_frame, clip_parent_end_frame]` should be sufficient to map to features of the clip.
